### ISSUE TITLE
firefox works but REAME.md doesn't state that

### ISSUE THREAD

**Issue by RossComputerGuy** [KaiWedekind/anycontrol#1]
Can you please add firefox to the list of supported browsers?

**Comment by KaiWedekind** [comment]
Hi, thank you for opening this issue.
Firefox is still not supported for what I have found.

- https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
- https://caniuse.com/#search=SpeechRecognition

If you have a workaround for Firefox, I'm interested to see what that is.
That might be worth adding to the README.md.

**Comment by KaiWedekind** [comment]
I'm closing this issue, feel free to reopen it at any time
