### ISSUE TITLE
hi, great script

### ISSUE THREAD

**Issue by inglesuniversal** [KaiWedekind/anycontrol#2]
how can I add two or more params at the same time

command
send message to USER saying THIS_TEXT and sent it at SPECIFIED_TIME

or

command
MY_ASSISTANT what TIME is it? (using keywords)

**Comment by Bkmillanzi** [comment]
> how can I add two or more params at the same time
> 
> command
> send message to USER saying THIS_TEXT and sent it at SPECIFIED_TIME
> 
> or
> 
> command
> MY_ASSISTANT what TIME is it? (using keywords)

It seems like the Admin is no longer responsive...

**Comment by KaiWedekind** [comment]
@inglesuniversal, @Bkmillanzi 
I have updated the version to 0.2.0 and updated the README.md with examples.
Let me know if you are running in issues.
Thanks, and happy new year! 🥳 

I'm going to close this issue for now, feel free to reopen it at any time.

**Comment by inglesuniversal** [comment]
AMAZING WORK!!!

Result {USER: "michael", transcript: "hello siri send a message to michael saying hi there and send it at 2 p.m.", THIS_TEXT: "hi there", SPECIFIED_TIME: "2 p.m."}
index.html:36 Result {USER: "george", transcript: "send a message to george saying hello and send it at 1 p.m.", THIS_TEXT: "hello", SPECIFIED_TIME: "1 p.m."}

**Comment by inglesuniversal** [comment]
now... can the previous parameters work for a case like this?

$ASSISTANT what is 2 times 5 

expected result:      The result of 2 times 5 equals 10



scenario 2



How to implement variations of a single command?


* Who's the president of _________
or
* Who is the president of ________



THANKS!!!! And have an amazing 2020!!!!

**Comment by KaiWedekind** [comment]
@inglesuniversal 

Yess, switch to 0.2.1 and follow the README examples or try the index.html examples in examples folder.
